name: Deploy to Live

on:
  push:
    tags:
    - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      version: ${{ github.ref_name }}
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRETKEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: NPM Setup
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Build and Deploy
      run: |
        npm install
        npm run build
        npm run deploy:live
